from ..core.manning.schemas import ChannelInput, ChannelResult, Units

def to_markdown(params: ChannelInput, result: ChannelResult) -> str:
    """Export calculation to markdown format."""
    unit_q = "m³/s" if params.units == Units.METRIC else "ft³/s"
    unit_len = "m" if params.units == Units.METRIC else "ft"
    unit_v = "m/s" if params.units == Units.METRIC else "ft/s"
    unit_a = "m²" if params.units == Units.METRIC else "ft²"

    md = f"""# Channel Calculation Analysis
**Generated:** {result.timestamp}
**Channel Type:** {params.type.value.capitalize()}

## Input Parameters
| Parameter | Value | Units |
|-----------|-------|-------|
| Discharge (Q) | {params.discharge} | {unit_q} |
"""
    if params.type != "triangular":
        md += f"| Bottom Width (b) | {params.bottom_width} | {unit_len} |\n"
    if params.type != "rectangular":
        md += f"| Side Slope (z:1) | {params.side_slope} | H:V |\n"
    
    md += f"""| Channel Slope (S) | {params.slope} | m/m |
| Manning's n | {params.mannings_n} | — |
| Units System | {params.units.value} | — |

## Hydraulic Results
| Result Property | Value | Units |
|-----------------|-------|-------|
| **Normal Depth (y_n)** | **{result.depth:.4f}** | **{unit_len}** |
| Flow Area (A) | {result.area:.3f} | {unit_a} |
| Wetted Perimeter (P) | {result.wetted_perimeter:.3f} | {unit_len} |
| Hydraulic Radius (R) | {result.hydraulic_radius:.3f} | {unit_len} |
| Velocity (V) | {result.velocity:.3f} | {unit_v} |
| Froude Number (Fr) | {result.froude_number:.3f} | — |
| Top Width (T) | {result.top_width:.3f} | {unit_len} |
| **Flow Regime** | **{result.flow_regime}** | — |

---
*Generated by Hydro Agent*
"""
    return md

def to_csv(params: ChannelInput, result: ChannelResult) -> str:
    """Export calculation to CSV format."""
    import csv
    import io

    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow(["Category", "Parameter", "Value", "Units"])
    
    # Inputs
    writer.writerow(["Input", "Type", params.type.value, ""])
    writer.writerow(["Input", "Discharge", params.discharge, "m³/s" if params.units == Units.METRIC else "ft³/s"])
    writer.writerow(["Input", "Bottom Width", params.bottom_width, "m" if params.units == Units.METRIC else "ft"])
    writer.writerow(["Input", "Side Slope", params.side_slope, "H:V"])
    writer.writerow(["Input", "Slope", params.slope, "m/m"])
    writer.writerow(["Input", "Manning's n", params.mannings_n, ""])
    
    # Results
    writer.writerow(["Result", "Normal Depth", result.depth, "m" if params.units == Units.METRIC else "ft"])
    writer.writerow(["Result", "Area", result.area, "m²" if params.units == Units.METRIC else "ft²"])
    writer.writerow(["Result", "Velocity", result.velocity, "m/s" if params.units == Units.METRIC else "ft/s"])
    writer.writerow(["Result", "Froude", result.froude_number, ""])
    writer.writerow(["Result", "Regime", result.flow_regime, ""])
    
    return output.getvalue()

def to_plain_text(params: ChannelInput, result: ChannelResult) -> str:
    """Plain text format - ultra simple for LLM prompts."""
    unit_len = "m" if params.units == Units.METRIC else "ft"
    
    text = f"HYDRO ANALYSIS REPORT\n"
    text += f"Type: {params.type.value}\n"
    text += f"Q={params.discharge}, S={params.slope}, n={params.mannings_n}\n"
    if params.type != "triangular": text += f"b={params.bottom_width}\n"
    if params.type != "rectangular": text += f"z={params.side_slope}\n"
    text += f"---\n"
    text += f"Normal Depth: {result.depth:.4f} {unit_len}\n"
    text += f"Velocity: {result.velocity:.3f}\n"
    text += f"Regime: {result.flow_regime}\n"
    return text
